# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
     #{id: 0, size: 0.069},
     #{id: 0, size: 0.0865},
     #{id: 0, size: 0.12},
     {id: 0, size: 0.112},
     {id: 1, size: 0.069},
     {id: 2, size: 0.069},
     {id: 3, size: 0.069},
     {id: 4, size: 0.069}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
tag_bundles:
  [
  
#    {
#      name: 'tag_0',
#      layout:
#        [
#          {id: 0, size: 0.08, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
#        ]
#    }
  ]
#tag_bundles:
#  [
#  ]
